# permissions for end users to view checkpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: checkpoint-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: checkpoint-viewer-role
rules:
- apiGroups:
  - apps.crsc.io
  resources:
  - checkpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.crsc.io
  resources:
  - checkpoints/status
  verbs:
  - get
