apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  annotations:
    crsc.io/checkpoint-restore: "true"
    crsc.io/checkpoint-interval: 450s
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "3600"]
